### ISSUE TITLE
Checklist: Querent Helm Charts and Release

### ISSUE THREAD

**Issue by saraswatpuneet** [Querent-ai/helm-charts#2]
## Details

Listing all (and will continue to add) the check list at which we can say Querent is ready to be deployed to cloud.

- [ ] Helm related artifacts verified.
- [ ] Hosting helm at github pages.
- [ ] Setup ci/lint
- [ ] Setup release for charts
- [ ] Test ...
